name: Deploy SST Stack DEV
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::155983569635:role/github-actions-oidc
          aws-region: eu-west-1
      - name: Install packages
        run: |
          npm install -g pnpm
          pnpm install
      - name: Deploy SST Stack
        run: |
          pnpm sst deploy --stage dev
